"""empty message

Revision ID: 24255a11ded7
Revises: b1fc1c697250
Create Date: 2020-07-22 23:46:44.609407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24255a11ded7'
down_revision = 'b1fc1c697250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('genre', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genre')
    # ### end Alembic commands ###
